export default {
  login: { title: 'Welcome back', intro: 'Sign in to continue to your shelf, sources, reading progress, and bookmarks.', username: 'Username', password: 'Password', submit: 'Sign in', submitting: 'Signing in…', failed: 'Sign in failed.', help: 'Account help', register: 'Create account', reset: 'Use reset token', recovery: 'Administrator recovery', expired: 'Your session ended. Sign in again to continue.', passwordChanged: 'Password changed. Sign in again with your new password.', logoutFailed: 'Private account state was closed, but the server could not confirm session revocation.', retryLogout: 'Retry sign out' },
  register: { title: 'Create reader account', intro: 'Your shelf, sources, progress, and files are kept in a private reader home.', invite: 'Invite code', submit: 'Create account', submitting: 'Creating account…', failed: 'Registration failed.' },
  reset: { title: 'Reset reader password', intro: 'Enter the one-time token from your Administrator and choose a new password. The token expires after 30 minutes.', token: 'Reset token', newPassword: 'New password', confirm: 'Confirm new password', mismatch: 'The new passwords do not match.', submit: 'Reset password', submitting: 'Resetting password…', failed: 'Password reset failed.', complete: 'Password reset complete. Sign in with your new password.' },
  setup: { title: 'Set up NovelReader', intro: 'Create the first Administrator account for this installation.', token: 'Bootstrap token', tokenHint: 'Paste the temporary ADMIN_BOOTSTRAP_TOKEN value configured on the server.', confirm: 'Confirm password', mismatch: 'The passwords do not match.', submit: 'Create Administrator', submitting: 'Creating account…', failed: 'Setup could not be completed.', aftercare: 'After setup succeeds, remove ADMIN_BOOTSTRAP_TOKEN from the server environment.', unavailableTitle: 'Setup requires server configuration', unavailableIntro: 'Set ADMIN_BOOTSTRAP_TOKEN, restart NovelReader, and reload this page.' },
  recovery: { title: 'Restore Administrator access', intro: 'Use the temporary recovery token configured on the server. Remove it from the environment when recovery is complete.', checking: 'Checking recovery configuration…', action: 'Recovery action', resetExisting: 'Reset an existing Administrator', createReplacement: 'Create a replacement Administrator', token: 'Recovery token', username: 'Administrator username', newPassword: 'New password', confirm: 'Confirm new password', mismatch: 'The passwords do not match.', submit: 'Recover and sign in', submitting: 'Recovering…', failed: 'Administrator recovery failed.', statusFailed: 'Recovery status could not be loaded.', unavailable: 'Administrator recovery is not enabled. Temporarily configure ADMIN_RECOVERY_TOKEN, restart the server, and return to this page.' },
  profile: { title: 'Account', description: 'Review your private reader identity, change its password, and manage the current browser session.', eyebrow: 'Reader identity', readerRole: 'Reader', adminRole: 'Administrator', manageReaders: 'Manage reader accounts' },
  security: { eyebrow: 'Security', title: 'Change password', description: 'A successful change revokes every browser session, including this one. You will need to sign in again.', current: 'Current password', new: 'New password', confirm: 'Confirm new password', hint: 'Use 12–128 characters.', submit: 'Change password', submitting: 'Changing password…', failed: 'Password change failed.', validation: { mismatch: 'The new passwords do not match.', tooShort: 'The new password must contain at least 12 characters.', tooLong: 'The new password cannot exceed 128 characters.', same: 'Choose a new password that differs from the current password.' } },
  session: { eyebrow: 'Current browser', title: 'Session', description: 'Sign out this browser without changing your password or reader data.', signOut: 'Sign out', signingOut: 'Signing out…', failed: 'The server could not revoke this session.' },
  readers: { title: 'Reader accounts', description: 'Manage ordinary reader access, issue one-time password resets, and remove reader homes. Administrator accounts are protected and never listed here.', loading: 'Loading reader accounts…', loadFailed: 'Reader accounts could not be loaded.', refresh: 'Refresh', search: 'Search', searchPlaceholder: 'Username or account ID', filter: 'Status', filters: { all: 'All accounts', active: 'Active', disabled: 'Disabled', deleting: 'Deleting' }, stats: { total: '{count} readers', active: '{count} active', disabled: '{count} disabled', deleting: '{count} deleting' }, status: { active: 'Active', disabled: 'Disabled', deleting: 'Deletion incomplete' }, created: 'Created {date}', updated: 'Updated {date}', enable: 'Enable', disable: 'Disable', statusFailed: 'Reader status could not be changed.', close: 'Close', cancel: 'Cancel', empty: { title: 'No reader accounts', description: 'Ordinary reader accounts will appear here after registration.', filteredTitle: 'No matching readers', filteredDescription: 'Try a different search or status filter.' }, notice: { enabled: '{username} can sign in again.', disabled: '{username} was disabled and existing sessions were revoked.', deleted: '{username} and its private reader home were deleted.' }, reset: { action: 'Issue reset token', eyebrow: 'Password recovery', title: 'Issue password reset', description: 'Create a one-time token for this reader. They complete the reset from the public password-reset page.', invalidates: 'Issuing a token invalidates any earlier unused reset token for this reader.', issue: 'Issue one-time token', issuing: 'Issuing token…', failed: 'The reset token could not be issued.', once: 'This plaintext token is shown only now. Copy it before closing this dialog.', token: 'One-time reset token', expires: 'Expires {time}', copy: 'Copy token', copied: 'Copied' }, delete: { action: 'Delete account', retry: 'Retry deletion', eyebrow: 'Permanent removal', title: 'Delete reader account', description: 'Deletion revokes sessions, drains active work, removes the private reader home, and removes the account.', warning: 'This cannot be undone. If deletion is interrupted, retrying continues the durable deletion job.', confirm: 'Type {username} exactly to confirm', deleting: 'Deleting…', failed: 'Account deletion did not complete. Retry to continue.', } },
  common: { backToLogin: 'Back to sign in' },
};
