export default {
  login: { title: 'Welcome back', intro: 'Sign in to continue to your shelf, sources, reading progress, and bookmarks.', username: 'Username', password: 'Password', submit: 'Sign in', submitting: 'Signing in…', failed: 'Sign in failed.', help: 'Account help', register: 'Create account', reset: 'Use reset token', recovery: 'Administrator recovery', expired: 'Your session ended. Sign in again to continue.', passwordChanged: 'Password changed. Sign in again with your new password.', logoutFailed: 'Private account state was closed, but the server could not confirm session revocation.', retryLogout: 'Retry sign out' },
  register: { title: 'Create reader account', intro: 'Your shelf, sources, progress, and files are kept in a private reader home.', invite: 'Invite code', submit: 'Create account', submitting: 'Creating account…', failed: 'Registration failed.' },
  reset: { title: 'Reset reader password', intro: 'Enter the one-time token from your Administrator and choose a new password. The token expires after 30 minutes.', token: 'Reset token', newPassword: 'New password', confirm: 'Confirm new password', mismatch: 'The new passwords do not match.', submit: 'Reset password', submitting: 'Resetting password…', failed: 'Password reset failed.', complete: 'Password reset complete. Sign in with your new password.' },
  setup: { title: 'Set up NovelReader', intro: 'Create the first Administrator account for this installation.', token: 'Bootstrap token', tokenHint: 'Paste the temporary ADMIN_BOOTSTRAP_TOKEN value configured on the server.', confirm: 'Confirm password', mismatch: 'The passwords do not match.', submit: 'Create Administrator', submitting: 'Creating account…', failed: 'Setup could not be completed.', aftercare: 'After setup succeeds, remove ADMIN_BOOTSTRAP_TOKEN from the server environment.', unavailableTitle: 'Setup requires server configuration', unavailableIntro: 'Set ADMIN_BOOTSTRAP_TOKEN, restart NovelReader, and reload this page.' },
  recovery: { title: 'Restore Administrator access', intro: 'Use the temporary recovery token configured on the server. Remove it from the environment when recovery is complete.', checking: 'Checking recovery configuration…', action: 'Recovery action', resetExisting: 'Reset an existing Administrator', createReplacement: 'Create a replacement Administrator', token: 'Recovery token', username: 'Administrator username', newPassword: 'New password', confirm: 'Confirm new password', mismatch: 'The passwords do not match.', submit: 'Recover and sign in', submitting: 'Recovering…', failed: 'Administrator recovery failed.', statusFailed: 'Recovery status could not be loaded.', unavailable: 'Administrator recovery is not enabled. Temporarily configure ADMIN_RECOVERY_TOKEN, restart the server, and return to this page.' },
  profile: { title: 'Account', description: 'Review your private reader identity, change its password, and manage the current browser session.', eyebrow: 'Reader identity', readerRole: 'Reader', adminRole: 'Administrator', manageReaders: 'Manage reader accounts' },
  security: { eyebrow: 'Security', title: 'Change password', description: 'A successful change revokes every browser session, including this one. You will need to sign in again.', current: 'Current password', new: 'New password', confirm: 'Confirm new password', hint: 'Use 12–128 characters.', submit: 'Change password', submitting: 'Changing password…', failed: 'Password change failed.', validation: { mismatch: 'The new passwords do not match.', tooShort: 'The new password must contain at least 12 characters.', tooLong: 'The new password cannot exceed 128 characters.', same: 'Choose a new password that differs from the current password.' } },
  session: { eyebrow: 'Current browser', title: 'Session', description: 'Sign out this browser without changing your password or reader data.', signOut: 'Sign out', signingOut: 'Signing out…', failed: 'The server could not revoke this session.' },
  common: { backToLogin: 'Back to sign in' },
};
