export default {
  brand: { tagline: 'Leave more time for the story', description: 'Discover, save, and read long-form books from your self-hosted sources.' },
  common: { retry: 'Try again', loading: 'Loading…', unknownAuthor: 'Unknown author', language: 'Language' },
  navigation: { app: 'Application navigation', reading: 'Reading', management: 'Management', primary: 'Primary navigation', shelf: 'Shelf', explore: 'Explore', search: 'Search', sources: 'Book sources', settings: 'Settings', account: 'Account', backups: 'Backup & restore', readers: 'Management', signOut: 'Sign out', signOutUser: 'Sign out {username}', accountManagement: 'Account and management' },
  startup: { opening: 'Opening NovelReader…', title: 'NovelReader could not start', fallback: 'NovelReader could not start.', offlineTitle: 'You’re offline', offlineDescription: 'NovelReader’s interface is available, but your shelf and books require a connection to your server.', unreachableTitle: 'Your NovelReader server is unavailable', unreachableDescription: 'The app is ready, but it cannot reach your self-hosted server. Check the connection and try again.' },
  webviewFailureHint: { message: 'If this source requires browser execution, verify the WebView worker before treating the source as broken.', action: 'Check WebView status' },
  notFound: { title: 'Page not found', description: 'This address does not exist or has moved.', action: 'Return to shelf' },
  planned: { note: 'This Vue page is being migrated against the existing backend contracts. No backend capability will be added from the prototype.', exploreTitle: 'Explore', exploreDescription: 'Choose one Explore-enabled source and browse its own categories, catalog, and sequential pages.', searchTitle: 'Search', searchDescription: 'Search enabled sources by title or author and merge results as they stream in.', detailTitle: 'Book details', detailDescription: 'View book information, chapters, and discovered sources.', readerTitle: 'Reader', readerDescription: 'A calm, responsive long-form reading experience.', sourcesTitle: 'Book source management', sourcesDescription: 'Import, inspect, and manage the sources owned by this account.', settingsTitle: 'Settings', settingsDescription: 'Manage global reading preferences, fonts, and interface settings.', accountTitle: 'Account', accountDescription: 'Change your password and review the current account.', backupsTitle: 'Backup & restore', backupsDescription: 'Export or replace this account’s Reader Data and manage scoped automation tokens.', readersTitle: 'Reader management', readersDescription: 'Administrators can enable, disable, reset, or delete ordinary reader accounts.' },
};
