export default {
  title: 'Search', description: 'Search enabled sources by title or author. Results appear progressively and equivalent books are consolidated without hiding their available sources.',
  form: { label: 'Book title or author', placeholder: 'Search by title or author…' },
  actions: { search: 'Search', stop: 'Stop', retry: 'Retry this batch', restart: 'Restart search', more: 'Scan {count} more sources' },
  controls: { title: 'Search coverage and intensity', batchSize: 'Sources per batch', intensity: 'Search intensity', gentle: 'Gentle · 4 concurrent', balanced: 'Balanced · 8 concurrent', fast: 'Fast · 16 concurrent', advanced: 'Advanced', concurrency: 'Concurrency' },
  status: { checkedOf: '{checked} of {eligible} searchable text sources checked', checked: '{checked} searchable text sources checked', results: '{count} books found', concurrency: 'Concurrency {count}', failures: '{count} source failures in completed batches', disconnected: 'The search connection was interrupted. Retry this batch to continue without losing results.', stale: 'The source list changed while searching. Restart the search.', storage: 'Search state could not be saved in this tab.' },
  results: { label: 'Search results', summary: '{count} consolidated books', multiple: '{count} have multiple sources', detailsFor: 'Preview {name}', preview: 'Preview book', sources: '{count} sources', shelve: 'Add to shelf', retryAdd: 'Retry sources', retryCommit: 'Try adding again', disconnected: 'Progress connection interrupted. Reconnecting…', cancelShelving: 'Cancel', cancelled: 'Adding was cancelled.', added: 'Added to your shelf.', addFailed: 'No known source could provide a readable copy of this book.' },
  empty: { title: 'No books found', description: 'Try another title or author, continue scanning if more sources are available, or check that searchable sources are enabled.' },
};
