import crypto from 'node:crypto';
import fs from 'node:fs';
const path='testdata/booksource/explore-live-audit-v11-2026-07-23.json';
const audit=JSON.parse(fs.readFileSync(path,'utf8'));
const corpus=fs.readFileSync(audit.corpus.path);
if(crypto.createHash('sha256').update(corpus).digest('hex')!==audit.corpus.sha256)throw Error('corpus hash mismatch');
if(audit.entries.length!==50||audit.selection.rawIndices.length!==50)throw Error('sample size mismatch');
const keys=audit.entries.map(e=>`${e.rawIndex}\0${e.bookSourceUrl}`);
if(new Set(keys).size!==50)throw Error('duplicate identities');
if(audit.entries.some(e=>!e.classification))throw Error('missing classification');
if(audit.entries.filter(e=>e.initial.page?.status!==200||!e.initial.page||e.initial.page.books===0||e.initial.page.distinctBookUrls===0||e.initial.page.diagnostics?.length).some(e=>!e.sequential))throw Error('missing sequential confirmation');
const counts={};for(const e of audit.entries)counts[e.classification]=(counts[e.classification]??0)+1;
if(JSON.stringify(counts)!==JSON.stringify(audit.summary.counts))throw Error('summary counts mismatch');
const books=audit.entries.filter(e=>e.classification==='credible_nonempty').reduce((n,e)=>n+(e.sequential?.page?.distinctBookUrls??e.initial.page?.distinctBookUrls??0),0);
if(books!==audit.summary.totalDistinctBooks)throw Error('book total mismatch');
const prior=new Set();for(const name of audit.selection.priorManifests){const j=JSON.parse(fs.readFileSync(`testdata/booksource/${name}`,'utf8'));for(const e of j.entries??[])prior.add(`${e.rawIndex}\0${e.bookSourceUrl??e.sourceUrl}`)}
if(prior.size!==450)throw Error(`prior identity count ${prior.size}`);
if(keys.some(k=>prior.has(k)))throw Error('sample overlaps prior audit');
const corpusJSON=JSON.parse(corpus);if(keys.some((key,i)=>key!==`${audit.entries[i].rawIndex}\0${corpusJSON[audit.entries[i].rawIndex].bookSourceUrl}`))throw Error('identity mismatch');
const eligible=corpusJSON.flatMap((source,rawIndex)=>{const sourceUrl=source.bookSourceUrl,key=`${rawIndex}\0${sourceUrl}`;if(source.enabled===false||!String(source.exploreUrl??'').trim()||prior.has(key))return[];return[{rawIndex,sourceUrl,name:source.bookSourceName,rank:crypto.createHash('sha256').update(`${audit.seed}\0${rawIndex}\0${sourceUrl}`).digest('hex')}]}).sort((a,b)=>a.rank.localeCompare(b.rank));
if(eligible.length!==audit.selection.eligibleRemainingBeforeSelection)throw Error('eligible count mismatch');
const expected=eligible.slice(0,audit.selection.size);
if(JSON.stringify(expected)!==JSON.stringify(audit.selection.identities))throw Error('ranked identities mismatch');
if(JSON.stringify(expected.map(e=>e.rawIndex))!==JSON.stringify(audit.selection.rawIndices))throw Error('ranked raw indices mismatch');
if(JSON.stringify(expected.map(e=>`${e.rawIndex}\0${e.sourceUrl}`))!==JSON.stringify(keys))throw Error('entry order mismatch');
for(const raw of [54,220,443,701])if(!audit.gapProbes?.[raw])throw Error(`missing gap probe ${raw}`);
const slow=audit.gapProbes[220];if(slow.direct?.httpStatus!==200||slow.direct?.bodyBytes!==52338||slow.direct?.matchingRows!==100||slow.direct?.bodySHA256!=='cf74b47e6f77d2442cf3f4b0168667eb9133b1be9e9a37031c9f9a02b67e7354')throw Error('incomplete raw 220 direct probe');
if(JSON.stringify(slow.productionReplays)!==JSON.stringify([{status:502,durationMs:10002,books:0,code:'transport_failed'},{status:200,durationMs:3848,books:100,code:null},{status:502,durationMs:10002,books:0,code:'transport_failed'}]))throw Error('incomplete raw 220 deadline comparison');
const regex=audit.gapProbes[701];if(regex.bodySHA256!=='39abe9528efa384f6b335fbae799952b9596a0cc6adf79f5bf075cf38d7af65c'||regex.matchingCards!==30||regex.runtime?.[0]?.error!=='regex: replace compile: error parsing regexp: invalid escape sequence: `\\简`'||regex.runtime?.[1]?.error!=='regex: replace compile: error parsing regexp: invalid escape sequence: `\\更`')throw Error('incomplete raw 701 runtime probe');
const range=audit.gapProbes[54];if(range.bodySHA256!=='5231a5b9e4ac303c2a893c1d79548c4dd5ef2207d1618e8051aeb85cb55b1a32'||range.currentShowLinks!==192||range.runtime?.[0]?.rule!=='ul li a'||range.runtime?.[0]?.elements!==188||range.runtime?.[1]?.rule!=='ul li a[8:]'||range.runtime?.[1]?.elements!==0||range.runtime?.[1]?.error!=='analyzer: no elements matched')throw Error('incomplete raw 54 runtime probe');
const structured=audit.gapProbes[443];if(structured.bodySHA256!=='829aebdfbf07b30864cad3b5642b46428d224f56d195cb90e7e79f3ddece62d9'||structured.listObjects!==12||structured.runtime?.[0]?.contentType!=='serialized string'||structured.runtime?.[0]?.value!==''||structured.runtime?.[0]?.error!=='analyzer: no elements matched'||structured.runtime?.[1]?.contentType!=='map[string]interface {}'||structured.runtime?.[1]?.value!=='妖神记'||structured.runtime?.[1]?.error!==null)throw Error('incomplete raw 443 runtime probe');
console.log(`v11 evidence valid: 50 unique, 450 excluded, ${books} distinct books`);
