import crypto from 'node:crypto';
import fs from 'node:fs';
const path='testdata/booksource/explore-live-audit-v12-2026-07-31.json';
const audit=JSON.parse(fs.readFileSync(path,'utf8'));
const corpusBytes=fs.readFileSync(audit.corpus.path);
if(crypto.createHash('sha256').update(corpusBytes).digest('hex')!==audit.corpus.sha256)throw Error('corpus hash mismatch');
if(audit.entries.length!==50||audit.selection.rawIndices.length!==50)throw Error('sample size mismatch');
const keys=audit.entries.map(e=>`${e.rawIndex}\0${e.bookSourceUrl}`);
if(new Set(keys).size!==50)throw Error('duplicate identities');
if(audit.entries.some(e=>!e.classification||!e.evidence))throw Error('missing classification/evidence');
const needsSequential=e=>e.initial.catalog.status!==200||!e.initial.page||e.initial.page.status!==200||e.initial.page.books===0||e.initial.page.distinctBookUrls===0||e.initial.page.diagnostics?.length;
if(audit.entries.filter(needsSequential).some(e=>!e.sequential))throw Error('missing sequential confirmation');
const counts={};for(const e of audit.entries)counts[e.classification]=(counts[e.classification]??0)+1;
if(JSON.stringify(counts)!==JSON.stringify(audit.summary.counts))throw Error('summary counts mismatch');
const books=audit.entries.filter(e=>e.classification==='credible_nonempty').reduce((n,e)=>n+(e.sequential?.page?.distinctBookUrls??e.initial.page?.distinctBookUrls??0),0);
if(books!==audit.summary.totalDistinctBooks||books!==2768)throw Error(`book total mismatch ${books}`);
const prior=new Set();for(const name of audit.selection.priorManifests){const j=JSON.parse(fs.readFileSync(`testdata/booksource/${name}`,'utf8'));for(const e of j.entries??[])prior.add(`${e.rawIndex}\0${e.bookSourceUrl??e.sourceUrl}`)}
if(prior.size!==500)throw Error(`prior identity count ${prior.size}`);
if(keys.some(k=>prior.has(k)))throw Error('sample overlaps prior audit');
const corpus=JSON.parse(corpusBytes);
for(const e of audit.entries)if(e.bookSourceUrl!==corpus[e.rawIndex].bookSourceUrl)throw Error(`identity mismatch ${e.rawIndex}`);
const eligible=corpus.flatMap((source,rawIndex)=>{const sourceUrl=source.bookSourceUrl,key=`${rawIndex}\0${sourceUrl}`;if(source.enabled===false||!String(source.exploreUrl??'').trim()||prior.has(key))return[];return[{rawIndex,sourceUrl,name:source.bookSourceName,rank:crypto.createHash('sha256').update(`${audit.seed}\0${rawIndex}\0${sourceUrl}`).digest('hex')}]}).sort((a,b)=>a.rank.localeCompare(b.rank));
if(eligible.length!==221||eligible.length!==audit.selection.eligibleRemainingBeforeSelection)throw Error(`eligible count mismatch ${eligible.length}`);
const expected=eligible.slice(0,50);
if(JSON.stringify(expected)!==JSON.stringify(audit.selection.identities))throw Error('ranked identities mismatch');
if(JSON.stringify(expected.map(e=>e.rawIndex))!==JSON.stringify(audit.selection.rawIndices))throw Error('ranked raw indices mismatch');
if(JSON.stringify(expected.map(e=>`${e.rawIndex}\0${e.sourceUrl}`))!==JSON.stringify(keys))throw Error('entry order mismatch');
const expectedCounts={engine_gap:4,source_incomplete_or_invalid:5,credible_nonempty:27,upstream_http:2,upstream_dns:3,site_drift:5,audit_infrastructure:1,stale_source_contract:2,blocked_or_auth:1};
if(JSON.stringify(audit.summary.counts)!==JSON.stringify(expectedCounts))throw Error('unexpected classifications');
for(const raw of [17,163,197,251])if(audit.entries.find(e=>e.rawIndex===raw)?.classification!=='engine_gap'||!audit.gapProbes?.[raw])throw Error(`missing gap evidence ${raw}`);
if(audit.gapProbes[251].mobile.productionBooksWithHeaderOnly!==7)throw Error('raw 251 probe incomplete');
if(audit.gapProbes[197].inner.decodedBooks!==15||audit.gapProbes[197].missingAPIs.length!==3)throw Error('raw 197 probe incomplete');
if(audit.gapProbes[163].matchingCards!==20||audit.gapProbes[163].equivalentRules.some(x=>x.books!==20))throw Error('raw 163 probe incomplete');
if(audit.gapProbes[17].matchingCards!==10||audit.gapProbes[17].runtime.supportedIndexAndNonblankNameBooks!==10)throw Error('raw 17 probe incomplete');
console.log(`v12 evidence valid: 50 unique, 500 excluded, ${books} distinct books, 4 gap identities`);
