<script lang="ts">
import { defineComponent, type PropType } from 'vue';
import type { Font } from '../../api/reader';
import type { ReaderPreferences } from './reader-preferences';
import AppButton from '../../ui/components/AppButton.vue';

export default defineComponent({ name: 'ReaderSettingsSheet', components: { AppButton }, props: { modelValue: { type: Object as PropType<ReaderPreferences>, required: true }, fonts: { type: Array as PropType<Font[]>, default: () => [] } }, emits: ['update:modelValue', 'close'], methods: { update(key: keyof ReaderPreferences, value: string | number) { this.$emit('update:modelValue', { ...this.modelValue, [key]: typeof this.modelValue[key] === 'number' ? Number(value) : value }); }, preset(background: string, textColor: string) { this.$emit('update:modelValue', { ...this.modelValue, background, textColor }); } } });
</script>
<template><div class="overlay" role="presentation" @click.self="$emit('close')" @keydown.esc="$emit('close')"><section class="sheet" role="dialog" aria-modal="true" :aria-label="$t('reader.settings.title')"><header><h2>{{ $t('reader.settings.title') }}</h2><AppButton variant="quiet" @click="$emit('close')">{{ $t('reader.close') }}</AppButton></header><label>{{ $t('reader.settings.fontSize') }} <input type="range" min="14" max="32" :value="modelValue.fontSize" @input="update('fontSize', ($event.target as HTMLInputElement).value)"><output>{{ modelValue.fontSize }}px</output></label><label>{{ $t('reader.settings.lineHeight') }} <input type="range" min="1.3" max="2.5" step=".05" :value="modelValue.lineHeight" @input="update('lineHeight', ($event.target as HTMLInputElement).value)"><output>{{ modelValue.lineHeight.toFixed(2) }}</output></label><label>{{ $t('reader.settings.pageWidth') }} <input type="range" min="480" max="1000" step="20" :value="modelValue.pageWidth" @input="update('pageWidth', ($event.target as HTMLInputElement).value)"><output>{{ modelValue.pageWidth }}px</output></label><label>{{ $t('reader.settings.weight') }} <select :value="modelValue.fontWeight" @change="update('fontWeight', ($event.target as HTMLSelectElement).value)"><option value="300">300</option><option value="400">400</option><option value="500">500</option><option value="700">700</option></select></label><label>{{ $t('reader.settings.font') }} <select :value="modelValue.fontId" @change="update('fontId', ($event.target as HTMLSelectElement).value)"><option value="system">{{ $t('reader.settings.systemFont') }}</option><option v-for="font in fonts" :key="font.id" :value="font.id">{{ font.name }}</option></select></label><div class="colors"><label>{{ $t('reader.settings.background') }} <input type="color" :value="modelValue.background" @input="update('background', ($event.target as HTMLInputElement).value)"></label><label>{{ $t('reader.settings.text') }} <input type="color" :value="modelValue.textColor" @input="update('textColor', ($event.target as HTMLInputElement).value)"></label></div><div class="presets"><button type="button" @click="preset('#f4eedc','#24333a')">{{ $t('reader.settings.sepia') }}</button><button type="button" @click="preset('#fffaf0','#24333a')">{{ $t('reader.settings.light') }}</button><button type="button" @click="preset('#20272a','#e8e1d2')">{{ $t('reader.settings.dark') }}</button></div></section></div></template>
<style scoped>.overlay{position:fixed;z-index:90;inset:0;display:flex;align-items:flex-end;justify-content:center;background:rgb(0 0 0/.38)}.sheet{width:min(44rem,100%);max-height:82dvh;overflow:auto;display:grid;gap:1rem;padding:1.1rem;border-radius:var(--radius-lg) var(--radius-lg) 0 0;background:var(--color-paper-raised);color:var(--color-ink)}header{display:flex;align-items:center;justify-content:space-between;gap:1rem}h2{margin:0;font:700 1.25rem var(--font-literary)}label{display:grid;grid-template-columns:9rem minmax(0,1fr) auto;gap:.7rem;align-items:center}select{min-height:2.75rem;border:1px solid var(--color-border);border-radius:var(--radius-md);padding:.5rem;background:white}.colors,.presets{display:flex;flex-wrap:wrap;gap:.75rem}.colors label{grid-template-columns:auto auto}.presets button{min-height:2.75rem;border:1px solid var(--color-border);border-radius:var(--radius-md);padding:.55rem .8rem;background:var(--color-paper-muted);color:var(--color-ink)}@media(max-width:36rem){label{grid-template-columns:1fr auto}label input[type=range],label select{grid-column:1/-1}.colors label{grid-template-columns:auto auto}}</style>