export default {
  login: { title: '歡迎回來', intro: '登入後繼續存取你的書架、書源、閱讀進度與書籤。', username: '使用者名稱', password: '密碼', submit: '登入', submitting: '正在登入…', failed: '登入失敗。', help: '帳戶協助', register: '建立帳戶', reset: '使用重設權杖', recovery: '管理員復原', expired: '登入已過期，請重新登入後繼續。', passwordChanged: '密碼已變更，請使用新密碼重新登入。', logoutFailed: '私人帳戶介面已關閉，但伺服器未能確認工作階段撤銷。', retryLogout: '重試登出' },
  register: { title: '建立閱讀帳戶', intro: '你的書架、書源、進度與檔案會保存在獨立的私人閱讀空間中。', invite: '邀請碼', submit: '建立帳戶', submitting: '正在建立…', failed: '建立帳戶失敗。' },
  reset: { title: '重設閱讀帳戶密碼', intro: '輸入管理員提供的一次性權杖並設定新密碼。權杖將在 30 分鐘後失效。', token: '重設權杖', newPassword: '新密碼', confirm: '確認新密碼', mismatch: '兩次輸入的密碼不一致。', submit: '重設密碼', submitting: '正在重設…', failed: '密碼重設失敗。', complete: '密碼重設完成，請使用新密碼登入。' },
  setup: { title: '設定 NovelReader', intro: '為此安裝建立第一個管理員帳戶。', token: '初始化權杖', tokenHint: '貼上伺服器設定中的 ADMIN_BOOTSTRAP_TOKEN 暫時值。', confirm: '確認密碼', mismatch: '兩次輸入的密碼不一致。', submit: '建立管理員', submitting: '正在建立…', failed: '初始化失敗。', aftercare: '設定成功後，請從伺服器環境中移除 ADMIN_BOOTSTRAP_TOKEN。', unavailableTitle: '伺服器尚未開放初始化', unavailableIntro: '請設定 ADMIN_BOOTSTRAP_TOKEN，重新啟動 NovelReader，然後重新整理此頁面。' },
  recovery: { title: '復原管理員存取權', intro: '使用伺服器暫時設定的復原權杖。完成後請立即移除該環境變數。', checking: '正在檢查復原設定…', action: '復原方式', resetExisting: '重設現有管理員', createReplacement: '建立替代管理員', token: '復原權杖', username: '管理員使用者名稱', newPassword: '新密碼', confirm: '確認新密碼', mismatch: '兩次輸入的密碼不一致。', submit: '復原並登入', submitting: '正在復原…', failed: '管理員復原失敗。', statusFailed: '無法讀取復原狀態。', unavailable: '伺服器未啟用管理員復原。請暫時設定 ADMIN_RECOVERY_TOKEN，重新啟動後再返回此頁面。' },
  profile: { title: '帳戶', description: '查看你的私人閱讀身分、變更密碼並管理目前瀏覽器工作階段。', eyebrow: '閱讀身分', readerRole: '閱讀帳戶', adminRole: '管理員', manageReaders: '管理閱讀帳戶' },
  security: { eyebrow: '安全', title: '變更密碼', description: '變更成功後會撤銷所有瀏覽器工作階段，包括目前工作階段。你需要重新登入。', current: '目前密碼', new: '新密碼', confirm: '確認新密碼', hint: '請輸入 12–128 個字元。', submit: '變更密碼', submitting: '正在變更密碼…', failed: '密碼變更失敗。', validation: { mismatch: '兩次輸入的新密碼不一致。', tooShort: '新密碼至少需要 12 個字元。', tooLong: '新密碼不能超過 128 個字元。', same: '新密碼必須與目前密碼不同。' } },
  session: { eyebrow: '目前瀏覽器', title: '工作階段', description: '登出目前瀏覽器，不會變更密碼或閱讀資料。', signOut: '登出', signingOut: '正在登出…', failed: '伺服器無法撤銷此工作階段。' },
  readers: { title: '閱讀帳戶', description: '管理一般閱讀帳戶的存取權、簽發一次性密碼重設權杖，並刪除私人閱讀空間。管理員帳戶受保護且不會列在此處。', loading: '正在載入閱讀帳戶…', loadFailed: '無法載入閱讀帳戶。', refresh: '重新整理', search: '搜尋', searchPlaceholder: '使用者名稱或帳戶 ID', filter: '狀態', filters: { all: '全部帳戶', active: '已啟用', disabled: '已停用', deleting: '正在刪除' }, stats: { total: '{count} 個閱讀帳戶', active: '{count} 個已啟用', disabled: '{count} 個已停用', deleting: '{count} 個刪除未完成' }, status: { active: '已啟用', disabled: '已停用', deleting: '刪除未完成' }, created: '建立於 {date}', updated: '更新於 {date}', enable: '啟用', disable: '停用', statusFailed: '無法變更閱讀帳戶狀態。', close: '關閉', cancel: '取消', empty: { title: '尚無閱讀帳戶', description: '一般使用者註冊後會顯示在這裡。', filteredTitle: '沒有符合的帳戶', filteredDescription: '請嘗試其他搜尋內容或狀態篩選。' }, notice: { enabled: '{username} 現在可以重新登入。', disabled: '已停用 {username} 並撤銷其現有工作階段。', deleted: '已刪除 {username} 及其私人閱讀空間。' }, reset: { action: '簽發重設權杖', eyebrow: '密碼復原', title: '簽發密碼重設權杖', description: '為此帳戶建立一次性權杖。使用者可在公開密碼重設頁面完成操作。', invalidates: '簽發新權杖會使此使用者先前未使用的重設權杖失效。', issue: '簽發一次性權杖', issuing: '正在簽發…', failed: '無法簽發重設權杖。', once: '明文權杖僅在此刻顯示。關閉對話框前請先複製。', token: '一次性重設權杖', expires: '到期時間：{time}', copy: '複製權杖', copied: '已複製' }, delete: { action: '刪除帳戶', retry: '重試刪除', eyebrow: '永久刪除', title: '刪除閱讀帳戶', description: '刪除會撤銷工作階段、等待正在進行的工作結束、移除私人閱讀空間並刪除帳戶。', warning: '此操作無法復原。如果刪除被中斷，請重試以繼續執行持久刪除工作。', confirm: '請輸入完全一致的 {username} 以確認', deleting: '正在刪除…', failed: '帳戶刪除尚未完成，請重試以繼續。' } },
  common: { backToLogin: '返回登入' },
};
