import fs from 'node:fs';
import { setTimeout as delay } from 'node:timers/promises';
const base='http://127.0.0.1:8899';
const initial=JSON.parse(fs.readFileSync('/tmp/explore-v11-initial.json','utf8'));
async function post(path,body,timeoutMs=95_000){const started=Date.now();try{const r=await fetch(base+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(timeoutMs)});const text=await r.text();let json;try{json=JSON.parse(text)}catch{json={rawBody:text.slice(0,2000)}}return{status:r.status,durationMs:Date.now()-started,body:json}}catch(e){return{status:0,durationMs:Date.now()-started,body:{code:e.name==='TimeoutError'?'audit_timeout':'audit_fetch_error',message:e.message}}}}
function choice(c){return(c?.entries??[]).find(x=>x.selectable&&x.type==='url')??(c?.entries??[]).find(x=>x.selectable)}
async function run(entry){const catalog=await post('/api/explore/catalog',{sourceId:entry.sourceUrl});const selected=catalog.status===200?choice(catalog.body):null;if(!selected)return{catalog,category:null,page:null};const page=await post('/api/explore/page',{sessionId:catalog.body.sessionId,categoryId:selected.id,page:1});const books=Array.isArray(page.body?.books)?page.body.books:[];return{catalog,category:{id:selected.id,title:selected.title,type:selected.type},page:{...page,bookCount:books.length,distinctBookUrls:new Set(books.map(x=>x.bookUrl).filter(Boolean)).size,exhausted:page.body?.exhausted??null,diagnostics:page.body?.diagnostics??[],sampleBooks:books.slice(0,2).map(x=>({name:x.name,author:x.author,bookUrl:x.bookUrl}))}}}
const targets=initial.entries.filter(e=>e.initial.catalog.status!==200||!e.initial.page||e.initial.page.status!==200||e.initial.page.bookCount===0||e.initial.page.distinctBookUrls===0||e.initial.page.diagnostics?.length);
const results=[];for(let i=0;i<targets.length;i++){const e=targets[i];const sequential=await run(e);results.push({...e,sequential});console.log(`${i+1}/${targets.length} raw=${e.rawIndex} catalog=${sequential.catalog.status} page=${sequential.page?.status??'-'} books=${sequential.page?.bookCount??0}`);fs.writeFileSync('/tmp/explore-v11-rerun.json',`${JSON.stringify({targets:results},null,2)}\n`);await delay(500)}
