<script lang="ts">
import { defineComponent } from 'vue';
import { changePassword } from '../../api/auth';
import { useSessionStore } from '../../stores/session';
import AppButton from '../../ui/components/AppButton.vue';
import FeatureScaffold from '../../ui/components/FeatureScaffold.vue';
import { clearedPasswordFields, roleLabelKey, validatePasswordChange } from './account-security';

export default defineComponent({
  name:'AccountView',components:{AppButton,FeatureScaffold},
  data(){return{...clearedPasswordFields(),submitting:false,error:'',signingOut:false}},
  computed:{account(){return useSessionStore().account},roleLabel():string{return this.account?this.$t(roleLabelKey(this.account.role)):''},initial():string{return this.account?.username.slice(0,1).toLocaleUpperCase()||'?'},isAdministrator():boolean{return useSessionStore().isAdministrator}},
  methods:{
    clearFields(){Object.assign(this,clearedPasswordFields())},
    async submit(){this.error='';const validation=validatePasswordChange(this);if(validation!=='ok'){this.error=this.$t(`account.security.validation.${validation}`);return}this.submitting=true;try{await changePassword(this.currentPassword,this.newPassword);this.clearFields();const session=useSessionStore();session.endAfterPasswordChange();await this.$router.replace('/login')}catch(cause){this.clearFields();this.error=cause instanceof Error?cause.message:this.$t('account.security.failed')}finally{this.submitting=false}},
    async signOut(){if(this.signingOut)return;this.signingOut=true;this.error='';try{await useSessionStore().logout()}catch{/* Login exposes retryable revocation failure. */}await this.$router.replace('/login');this.signingOut=false},
  }
});
</script>
<template><FeatureScaffold :title="$t('account.profile.title')" :description="$t('account.profile.description')"><div v-if="account" class="account"><section class="profile-card"><div class="avatar" aria-hidden="true">{{ initial }}</div><div class="identity"><p class="eyebrow">{{ $t('account.profile.eyebrow') }}</p><h2>{{ account.username }}</h2><span>{{ roleLabel }}</span><small>{{ account.id }}</small></div><RouterLink v-if="isAdministrator" class="admin-link" to="/account/readers">{{ $t('account.profile.manageReaders') }}</RouterLink></section><section class="security panel"><header><div><p class="eyebrow">{{ $t('account.security.eyebrow') }}</p><h2>{{ $t('account.security.title') }}</h2><p>{{ $t('account.security.description') }}</p></div></header><form @submit.prevent="submit"><label class="sr-only">{{ $t('account.login.username') }}<input :value="account.username" autocomplete="username" readonly tabindex="-1"></label><label>{{ $t('account.security.current') }}<input v-model="currentPassword" type="password" autocomplete="current-password" required maxlength="128" :disabled="submitting"></label><label>{{ $t('account.security.new') }}<input v-model="newPassword" type="password" autocomplete="new-password" required minlength="12" maxlength="128" :disabled="submitting"><small>{{ $t('account.security.hint') }}</small></label><label>{{ $t('account.security.confirm') }}<input v-model="confirmPassword" type="password" autocomplete="new-password" required minlength="12" maxlength="128" :disabled="submitting"></label><p v-if="error" class="error" role="alert">{{ error }}</p><AppButton type="submit" :busy="submitting">{{ submitting?$t('account.security.submitting'):$t('account.security.submit') }}</AppButton></form></section><section class="session panel"><div><p class="eyebrow">{{ $t('account.session.eyebrow') }}</p><h2>{{ $t('account.session.title') }}</h2><p>{{ $t('account.session.description') }}</p></div><AppButton variant="secondary" :busy="signingOut" @click="signOut">{{ signingOut?$t('account.session.signingOut'):$t('account.session.signOut') }}</AppButton></section></div></FeatureScaffold></template>
<style scoped>.account{display:grid;gap:1rem}.profile-card,.panel{padding:1rem;border:1px solid var(--color-border);border-radius:var(--radius-lg);background:var(--color-paper-raised)}.profile-card{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:1rem}.avatar{width:4rem;height:4rem;display:grid;place-items:center;border-radius:50%;background:linear-gradient(145deg,var(--color-accent),var(--color-accent-strong));color:white;font:700 1.5rem var(--font-literary)}.identity{min-width:0}.identity h2,.panel h2{margin:.15rem 0;font:700 1.3rem var(--font-literary)}.identity span{display:block;color:var(--color-warm);font-weight:700}.identity small{display:block;margin-top:.25rem;color:var(--color-ink-muted);overflow-wrap:anywhere}.eyebrow{margin:0;color:var(--color-warm)!important;font-size:.7rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.admin-link{min-height:2.75rem;display:inline-flex;align-items:center;border:1px solid var(--color-border);border-radius:var(--radius-md);padding:.6rem .85rem;text-decoration:none;font-weight:700}.panel header p,.session p{margin:.25rem 0 0;color:var(--color-ink-muted);line-height:1.55}.security form{max-width:36rem;display:grid;gap:.85rem;margin-top:1rem}.security label{display:grid;gap:.35rem;font-size:.8rem;font-weight:700}.security input{min-height:2.75rem;border:1px solid var(--color-border);border-radius:var(--radius-md);padding:.6rem .7rem;background:white;color:var(--color-ink)}.security label small{color:var(--color-ink-muted);font-weight:400}.security form :deep(.app-button){justify-self:start}.error{margin:0;padding:.7rem;border-radius:var(--radius-md);background:#f8e4df;color:var(--color-danger)}.session{display:flex;justify-content:space-between;align-items:center;gap:1.5rem}@media(max-width:38rem){.profile-card{grid-template-columns:auto minmax(0,1fr)}.admin-link{grid-column:1/-1;justify-content:center}.session{align-items:stretch;flex-direction:column}.session :deep(.app-button),.security form :deep(.app-button){width:100%;justify-self:stretch}}</style>
