<script lang="ts">
import { defineComponent, type PropType } from 'vue';
import type { AdminReaderAccount } from '../../api/auth';
import AppButton from '../../ui/components/AppButton.vue';
import { exactUsernameConfirmed } from './reader-administration';
export default defineComponent({name:'ReaderDeleteDialog',components:{AppButton},props:{account:{type:Object as PropType<AdminReaderAccount>,required:true},busy:Boolean,error:{type:String,default:''}},emits:['confirm','close'],data(){return{confirmation:''}},computed:{confirmed():boolean{return exactUsernameConfirmed(this.account,this.confirmation)}}});
</script>
<template><div class="overlay" @click.self="$emit('close')" @keydown.esc="$emit('close')"><section class="dialog" role="alertdialog" aria-modal="true" :aria-label="$t('account.readers.delete.title')"><header><div><p class="eyebrow">{{ $t('account.readers.delete.eyebrow') }}</p><h2>{{ account.username }}</h2></div><AppButton variant="quiet" :disabled="busy" @click="$emit('close')">{{ $t('account.readers.close') }}</AppButton></header><p>{{ $t('account.readers.delete.description') }}</p><p class="warning">{{ $t('account.readers.delete.warning') }}</p><label><span>{{ $t('account.readers.delete.confirm',{username:account.username}) }}</span><input v-model="confirmation" autocomplete="off" :disabled="busy"></label><p v-if="error" class="error" role="alert">{{ error }}</p><footer><AppButton variant="secondary" :disabled="busy" @click="$emit('close')">{{ $t('account.readers.cancel') }}</AppButton><AppButton variant="danger" :busy="busy" :disabled="!confirmed" @click="$emit('confirm',confirmation)">{{ busy?$t('account.readers.delete.deleting'):$t('account.readers.delete.action') }}</AppButton></footer></section></div></template>
<style scoped>.overlay{position:fixed;z-index:90;inset:0;display:flex;align-items:center;justify-content:center;padding:1rem;background:rgb(0 0 0/.42)}.dialog{width:min(34rem,100%);display:grid;gap:1rem;padding:1rem;border-radius:var(--radius-lg);background:var(--color-paper-raised)}header,footer{display:flex;justify-content:space-between;align-items:center;gap:1rem}footer{justify-content:flex-end}h2,p{margin:0}h2{font:700 1.35rem var(--font-literary)}.eyebrow{color:var(--color-warm);font-size:.7rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.warning{padding:.7rem;border-radius:var(--radius-md);background:#f8e4df;color:var(--color-danger)}label{display:grid;gap:.35rem;font-size:.78rem;font-weight:700}input{min-height:2.75rem;border:1px solid var(--color-border);border-radius:var(--radius-md);padding:.6rem .7rem}.error{color:var(--color-danger)}@media(max-width:34rem){.overlay{padding:0;align-items:flex-end}.dialog{border-radius:var(--radius-lg) var(--radius-lg) 0 0}footer{align-items:stretch;flex-direction:column-reverse}footer :deep(.app-button){width:100%}}</style>
