import { defineStore } from 'pinia';
import { getExplorePage, listExploreSources, openExplore, runExploreAction, updateExploreControl, type ExploreCatalog, type ExploreDiagnostic, type ExploreEntry, type ExploreSource } from '../../api/explore';
import type { SourceInteractionEffect } from '../../api/sources';
import type { SearchResult } from '../../api/models';
import { ExploreApiError } from '../../api/transport';
import { categorySelection, classifyExploreError, selectedCategoryAfterRefresh, type CachedExplorePage } from './explore-state';

const storageKey='novelreader.explore-session.v1';
interface Snapshot { sourceId:string; catalog:ExploreCatalog|null; categoryId:string; results:SearchResult[]; nextPage:number; exhausted:boolean; diagnostics:ExploreDiagnostic[]; cache:Record<string,CachedExplorePage> }

export const useExploreStore=defineStore('explore',{
  state:()=>({sources:[] as ExploreSource[],sourceId:'',catalog:null as ExploreCatalog|null,categoryId:'',results:[] as SearchResult[],nextPage:1,exhausted:false,diagnostics:[] as ExploreDiagnostic[],busy:'' as ''|'sources'|'catalog'|'control'|'page',error:'',retryable:false,initialized:false,generation:0,controller:null as AbortController|null,cache:{} as Record<string,CachedExplorePage>,retryAction:null as null|(()=>void)}),
  getters:{controls:(state)=>state.catalog?.entries.filter(entry=>['text','button','toggle','select'].includes(entry.type))||[],categories:(state)=>state.catalog?.entries.filter(entry=>entry.type==='url')||[],selectedSource:(state)=>state.sources.find(source=>source.id===state.sourceId)||state.catalog?.source||null},
  actions:{
    initialize(){if(this.initialized)return;this.initialized=true;try{const saved=JSON.parse(sessionStorage.getItem(storageKey)||'null') as Snapshot|null;if(!saved||typeof saved.sourceId!=='string')return;this.sourceId=saved.sourceId;this.catalog=saved.catalog;this.categoryId=saved.categoryId||'';this.results=Array.isArray(saved.results)?saved.results:[];this.nextPage=Math.max(1,saved.nextPage||1);this.exhausted=Boolean(saved.exhausted);this.diagnostics=Array.isArray(saved.diagnostics)?saved.diagnostics:[];this.cache=saved.cache||{}}catch{sessionStorage.removeItem(storageKey)}},
    save(){try{sessionStorage.setItem(storageKey,JSON.stringify({sourceId:this.sourceId,catalog:this.catalog,categoryId:this.categoryId,results:this.results,nextPage:this.nextPage,exhausted:this.exhausted,diagnostics:this.diagnostics,cache:this.cache}))}catch{/* tab restoration is optional */}},
    begin(kind:''|'sources'|'catalog'|'control'|'page'){this.controller?.abort();this.controller=new AbortController();this.busy=kind;this.error='';this.retryable=false;this.retryAction=null;return{generation:++this.generation,signal:this.controller.signal}},
    finish(generation:number){if(generation===this.generation)this.busy=''},
    resetResults(){this.categoryId='';this.results=[];this.nextPage=1;this.exhausted=false;this.diagnostics=[];this.cache={}},
    stop(){this.generation+=1;this.controller?.abort();this.controller=null;this.busy=''},
    async loadSources(){const request=this.begin('sources');try{const values=await listExploreSources(request.signal);if(request.generation!==this.generation)return;this.sources=values;if(this.sourceId&&!values.some(source=>source.id===this.sourceId)){this.sourceId='';this.catalog=null;this.resetResults();this.save()}}catch(cause){this.handleFailure(cause,request.generation,()=>this.loadSources())}finally{this.finish(request.generation)}},
    async openSource(id:string){this.sourceId=id;this.catalog=null;this.resetResults();this.save();if(!id)return;const request=this.begin('catalog');try{const catalog=await openExplore(id,request.signal);if(request.generation!==this.generation)return;this.catalog=catalog;this.diagnostics=catalog.diagnostics;this.save()}catch(cause){this.handleFailure(cause,request.generation,()=>this.openSource(id))}finally{this.finish(request.generation)}},
    refreshSource(id:string){this.initialize();if(id&&this.sourceId===id)void this.openSource(id)},
    async updateControl(entry:ExploreEntry,value:string|null){if(!this.catalog)return;const sessionId=this.catalog.sessionId;const request=this.begin('control');try{const refreshed=await updateExploreControl(sessionId,entry.id,value,request.signal);if(request.generation!==this.generation)return;const retained=selectedCategoryAfterRefresh(this.categoryId,refreshed.entries);this.catalog=refreshed;this.diagnostics=refreshed.diagnostics;this.results=[];this.nextPage=1;this.exhausted=false;this.cache={};this.categoryId=retained;this.save();if(retained)void this.loadPage(1,true)}catch(cause){this.handleFailure(cause,request.generation,()=>this.openSource(this.sourceId))}finally{this.finish(request.generation)}},
    async runAction(entry:ExploreEntry):Promise<SourceInteractionEffect[]>{if(!this.catalog)return[];const request=this.begin('control');try{const result=await runExploreAction(this.catalog.sessionId,entry.id,request.signal);if(request.generation!==this.generation)return[];return result.effects}catch(cause){this.handleFailure(cause,request.generation,()=>this.openSource(this.sourceId));return[]}finally{this.finish(request.generation)}},
    selectCategory(entry:ExploreEntry){const selection=categorySelection(this.categoryId,entry.id,this.cache);if(selection.kind==='current')return;this.categoryId=entry.id;if(selection.kind==='cached'){Object.assign(this,selection.state);this.save();return}this.results=[];this.nextPage=1;this.exhausted=false;this.save();void this.loadPage(1,true)},
    async loadPage(page:number,reset:boolean){if(!this.catalog||!this.categoryId)return;const sessionId=this.catalog.sessionId;const categoryId=this.categoryId;const request=this.begin('page');try{const response=await getExplorePage(sessionId,categoryId,page,request.signal);if(request.generation!==this.generation||this.categoryId!==categoryId)return;this.results=reset?response.books:[...this.results,...response.books];this.nextPage=response.nextPage;this.exhausted=response.exhausted;this.diagnostics=response.diagnostics;this.cache={...this.cache,[categoryId]:{results:this.results,nextPage:this.nextPage,exhausted:this.exhausted}};this.save()}catch(cause){const error=cause instanceof ExploreApiError?cause:null;const recovery=classifyExploreError(error);if(recovery.kind==='page')this.nextPage=recovery.page;this.handleFailure(cause,request.generation,()=>this.loadPage(this.nextPage,false))}finally{this.finish(request.generation)}},
    handleFailure(cause:unknown,generation:number,retry?:()=>void){if(generation!==this.generation||(cause instanceof DOMException&&cause.name==='AbortError'))return;const apiError=cause instanceof ExploreApiError?cause:null;const recovery=classifyExploreError(apiError);if(recovery.kind==='reopen'&&this.sourceId){this.catalog=null;this.resetResults();void this.openSource(this.sourceId);return}if(recovery.kind==='page')this.nextPage=recovery.page;this.error=cause instanceof Error?cause.message:'Explore request failed';this.retryable=recovery.kind!=='stop';this.retryAction=recovery.kind==='stop'?null:retry||null},
    retry(){const action=this.retryAction;this.retryAction=null;action?.()},
  }
});
